[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[fuzz]
runs = 256                    # Number of fuzz runs
max_test_rejects = 65536     # Max number of rejected inputs
dictionary_weight = 40       # Weight for dictionary usage
include_storage = true       # Include storage variables in fuzz inputs
include_push_bytes = true    # Include push bytes in fuzz inputs

[invariant]
runs = 256                   # Number of invariant runs
depth = 15                   # Depth of invariant calls
shrink_run_limit = 5000      # Shrinking for invariant tests

[lint]
lint_on_build = false
ignore = ["quotes"]